-- CREATING NEW DATABASE NAMED 'MEC'.
CREATE DATABASE MEC; 
-- SELECTING THE DATABASE TO CREATE TABLE. 
USE MEC;
-- CREATING TABLE. 
CREATE TABLE employees(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255),salary DOUBLE);
-- HERE TABLE NAME "employees".
-- COLUMN NAMES "id" , "name" , "salary.
-- HERE THE "id" COLUMN IS AUTO INCREMENT COLUMN AND ALSO PRIMARY.